* Movement
Keys 	Description
C-a 	Move to beginning of line
M-m 	Move to the first non-whitespace character on the line
C-e 	Move to end of line
C-f 	Move forward one character
C-b 	Move backward one character
M-f 	Move forward one word (I use this a lot)
M-b 	Move backward one word (I use this a lot, too)
C-s 	Regex search for text in the current buffer and move to it. Hit C-s again to move to the next match
C-r 	Same as above, but search in reverse
M-< 	Move to beginning of buffer
M-> 	Move to end of buffer
M-g g 	Go to line
* Kill/yank
Keys 	Description
C-w 	Kill region
M-w 	Copy region to kill ring
C-y 	Yank
M-y 	Cycle through kill ring after yanking
M-d 	Kill word
C-k 	Kill line
* Editing
Keys 	Description
Tab 	Indent line
C-j 	New line and indent, equivalent to "enter" followed by "tab"
M-/ 	Hippie expand, cycles through possible expansions of the text before point
M-\ 	Delete all spaces and tabs around point. I use this one a lot
* Help
Keys 	Description
C-h k (key) 	Describes the function bound to the keybinding. To get this to work, you actually perform the key sequence after typing C-h k
C-h f 	Describe function
* Screen Handling
Keys 	Description
C-x o 	Switch cursor to another window. Go ahead and try this now to switch between your Clojure file and the REPL
C-x 1 	Delete all other windows. This doesn't close your buffers and it won't cause you to lose any work. It just un-splits your frame.
C-x 2 	Split window, above and below
C-x 3 	Split window, side by side
C-x 0 	Delete current window

* Clojure Buffer Key Bindings
Keys 	        Description
C-c M-n 	Switch to namespace of the current buffer
C-x C-e 	Evaluate the expression immediately preceding point
C-c C-k 	Compile current buffer
C-c C-d C-d 	Display documentation for symbol under point.
M-. and M-, 	Navigate to source code for symbol under point and return to your original buffer.
C-c C-d C-a 	Apropros search; find arbitrary text across function names and documentation.
* CIDER Buffer Key Bindings
Keys 	        Description
C-↑, C-↓ 	Cycle through CIDER history
C-↵ 	        Close parentheses and evaluate
* Paredit
Keys 	Description
M-x paredit-mode 	Toggle paredit mode
M-( 	paredit-wrap-round, surround expression after point in parentheses
C-→ 	Slurp; move closing parenthesis to the right to include next expression
C-← 	Barf; move closing parenthesis to the left to exclude last expression
C-M-f, C-M-b 	Move to the opening/closing parenthesis
* midje
(use 'midje.repl)
(autotest)
